# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000ms
    servlet:
        context-path: /mansys

spring:
    file:
        #文件管理和合同文件的上传路径（window）
        uploadFolder: /home/ubuntu/upload/file/
        upContractFolder: /home/ubuntu/upload/contract/
        upReportFolder: /home/ubuntu/upload/report/
        downImgFolder: E/home/ubuntu/upload/mainImg/
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/man?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ygg654321

logging:
    file: ./springbootlog/pro.log



